nome = str(input("Digite seu nome completo: ")).strip().capitalize()
primeiro_nome = nome.split()
print(f"Seu nome com letras maiúsculas: {nome.upper()}")
print(f"Seu nome com letras minúsculas: {nome.lower()}")
print(f"Seu nome possui {len(nome)-nome.count(' ')} letras.")
print(f"Seu primeiro nome é {primeiro_nome[0]} e tem {nome.find(' ')} letras.")
